# PyFileMaker 2.0 - Integrating FileMaker and Python 
# (c) 2002-2003 Pieter Claerhout, pieter@yellowduck.be
# 
# http://www.yellowduck.be/filemaker/

# Import the main modules
from exceptions import StandardError

# The error number to messages mapping
FMProErrorNum = {}
FMProErrorNum[-1] = 'Unknown error'
FMProErrorNum[0] = 'No error (success)'
FMProErrorNum[1] = 'User canceled action'
FMProErrorNum[2] = 'Memory error'
FMProErrorNum[3] = 'Command is unavailable (for example, wrong operating system, wrong mode, etc.)'
FMProErrorNum[4] = 'Command is unknown'
FMProErrorNum[5] = 'Command is invalid (for example, a Set Field script step does not have a calculation specified)'
FMProErrorNum[100] = 'File is missing'
FMProErrorNum[101] = 'Record is missing'
FMProErrorNum[102] = 'Field is missing'
FMProErrorNum[103] = 'Relationship is missing'
FMProErrorNum[104] = 'Script is missing'
FMProErrorNum[105] = 'Layout is missing'
FMProErrorNum[200] = 'Record access is denied'
FMProErrorNum[201] = 'Field cannot be modified'
FMProErrorNum[202] = 'Field access is denied'
FMProErrorNum[203] = 'No records in file to print or password doesn\'t allow print access'
FMProErrorNum[204] = 'No access to field(s) in sort order'
FMProErrorNum[205] = 'Cannot create new records; import will overwrite existing data'
FMProErrorNum[206] = 'Cannot change password or file is not modifiable'
FMProErrorNum[207] = 'Cannot access field definitions or file is not modifiable'
FMProErrorNum[300] = 'The file is locked or in use'
FMProErrorNum[301] = 'Record is in use by another user'
FMProErrorNum[302] = 'Script definitions are in use by another user'
FMProErrorNum[303] = 'Paper size is in use by another user'
FMProErrorNum[304] = 'Password definitions are in use by another user'
FMProErrorNum[305] = 'Relationship or value list definitions are in use by another user'
FMProErrorNum[306] = 'Record modification ID does not match'
FMProErrorNum[400] = 'Find criteria is empty'
FMProErrorNum[401] = 'No records match the request'
FMProErrorNum[402] = 'Selected field is not a match field for a lookup'
FMProErrorNum[403] = 'Exceeding maximum record limit for trial version of FileMaker Pro'
FMProErrorNum[404] = 'Sort order is invalid'
FMProErrorNum[405] = 'Number of records specified exceeds number of records that can be omitted'
FMProErrorNum[406] = 'Replace/Reserialize criteria is invalid'
FMProErrorNum[407] = 'One or both match fields are missing (invalid relationship)'
FMProErrorNum[408] = 'Specified field has inappropriate data type for this operation'
FMProErrorNum[409] = 'Import order is invalid'
FMProErrorNum[410] = 'Export order is invalid'
FMProErrorNum[411] = 'Cannot perform delete because related records cannot be deleted'
FMProErrorNum[412] = 'Wrong version of FileMaker Pro used to recover file'
FMProErrorNum[500] = 'Date value does not meet validation entry options'
FMProErrorNum[501] = 'Time value does not meet validation entry options'
FMProErrorNum[502] = 'Number value does not meet validation entry options'
FMProErrorNum[503] = 'Value in field is not within the range specified in validation entry options'
FMProErrorNum[504] = 'Value in field is not unique as required in validation entry options'
FMProErrorNum[505] = 'Value in field is not an existing value in the database as required in validation entry options'
FMProErrorNum[506] = 'Value in field is not listed on the value list specified in validation entry option'
FMProErrorNum[507] = 'Value in field failed calculation test of validation entry option'
FMProErrorNum[508] = 'Invalid value entered in Find mode'
FMProErrorNum[509] = 'Field requires a valid value'
FMProErrorNum[510] = 'Related value is empty or unavailable'
FMProErrorNum[511] = 'Value in field exceeds maximum number of allowed characters'
FMProErrorNum[600] = 'Print error has occurred'
FMProErrorNum[601] = 'Combined header and footer exceed one page'
FMProErrorNum[602] = 'Body doesn\'t fit on a page for current column setup'
FMProErrorNum[603] = 'Print connection lost'
FMProErrorNum[700] = 'File is of the wrong file type for import'
FMProErrorNum[701] = 'Data Access Manager can\'t find database extension file'
FMProErrorNum[702] = 'The Data Access Manager was unable to open the session'
FMProErrorNum[703] = 'The Data Access Manager was unable to open the session; try later'
FMProErrorNum[704] = 'Data Access Manager failed when sending a query'
FMProErrorNum[705] = 'Data Access Manager failed when executing a query'
FMProErrorNum[706] = 'EPSF file has no preview image'
FMProErrorNum[707] = 'Graphic translator cannot be found'
FMProErrorNum[708] = 'Can\'t import the file or need color computer to import file'
FMProErrorNum[709] = 'QuickTime movie import failed'
FMProErrorNum[710] = 'Unable to update QuickTime file reference because the database is read-only'
FMProErrorNum[711] = 'Import translator can not be found'
FMProErrorNum[712] = 'XTND version is incompatible'
FMProErrorNum[713] = 'Couldn\'t initialize the XTND system'
FMProErrorNum[714] = 'Password privileges do not allow the operation'
FMProErrorNum[715] = 'Specified Excel worksheet or named range is missing'
FMProErrorNum[716] = 'A SQL query using DELETE, INSERT, or UPDATE is not allowed for ODBC import'
FMProErrorNum[717] = 'There is not enough XML/XSL information to proceed with the import or export'
FMProErrorNum[718] = 'Error in parsing XML file (from Xalan)'
FMProErrorNum[719] = 'Error in transforming XML document (after XSL transformation)'
FMProErrorNum[720] = 'Error in parsing the XML document (after XSL transformation)'
FMProErrorNum[721] = 'Error when exporting--intended format does not support repeating fields'
FMProErrorNum[800] = 'Unable to create file on disk'
FMProErrorNum[801] = 'Unable to create temporary file on System disk'
FMProErrorNum[802] = 'Unable to open file'
FMProErrorNum[803] = 'File is single user or host cannot be found'
FMProErrorNum[804] = 'File cannot be opened as read-only in its current state'
FMProErrorNum[805] = 'File is damaged; use Recover command'
FMProErrorNum[806] = 'File cannot be opened with this version of FileMaker Pro'
FMProErrorNum[807] = 'File is not a FileMaker Pro file or is severely damaged'
FMProErrorNum[808] = 'Cannot open file because access privileges are damaged'
FMProErrorNum[809] = 'Disk/volume is full'
FMProErrorNum[810] = 'Disk/volume is locked'
FMProErrorNum[811] = 'Temporary file cannot be opened as FileMaker Pro file'
FMProErrorNum[812] = 'Cannot open the file because it exceeds host capacity'
FMProErrorNum[813] = 'Record Synchronization error on network'
FMProErrorNum[814] = 'File(s) cannot be opened because maximum number is open'
FMProErrorNum[815] = 'Couldn\'t open lookup file'
FMProErrorNum[816] = 'Unable to convert file'
FMProErrorNum[817] = 'Unable to open file because it does not belong to this solution'
FMProErrorNum[818] = 'FileMaker Pro cannot network for some reason'
FMProErrorNum[900] = 'General spelling engine error'
FMProErrorNum[901] = 'Main spelling dictionary not installed'
FMProErrorNum[902] = 'Could not launch the Help system'
FMProErrorNum[903] = 'Command cannot be used in a shared file'
FMProErrorNum[904] = 'Command can only be used in a file hosted under FileMaker Server'
FMProErrorNum[905] = 'No active field selected--command can only be used if there is an active field'
FMProErrorNum[950] = 'Adding repeating related fields is not supported'
FMProErrorNum[951] = 'An unexpected error occurred'
FMProErrorNum[952] = 'Mail format not found (Web Companion)'
FMProErrorNum[953] = 'Mail value missing (Web Companion)'
FMProErrorNum[971] = 'The user name is invalid'
FMProErrorNum[972] = 'The password is invalid'
FMProErrorNum[973] = 'The database is invalid'
FMProErrorNum[974] = 'Permission Denied'
FMProErrorNum[975] = 'The field has restricted access'
FMProErrorNum[976] = 'Security is disabled'
FMProErrorNum[977] = 'Invalid client IP address'
FMProErrorNum[978] = 'The number of allowed guests has been exceeded (for the 10 guest limit over a 12 hour period)'

# Exception related to operation with FMPro
class FMProError( StandardError ):
    pass

# This function raises an error based on the specified error code
def FMProErrorByNum( num ):
    if not num in FMProErrorNum.keys():
        raise FMProError, FMProErrorNum[-1]
    else:
        raise FMProError, FMProErrorNum[num]
